sudo: required
services:
    - docker
before_install:
# this comes from encrypting service-account.json file
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
# google cloud SDK installation
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
# authorization. Service account with admin access to kubernetes engine should have existed
    - gcloud auth activate-service-account --key-file service-account.json