apiVersion: apps/v1

kind: Deployment

metadata:
# names the object
    name: server-deployment
spec:
# number of pods this deployment is running
    replicas: 3
# master or some program in master creates the pod and we select it
    selector:
        matchLabels:
            component: server
# template applies to every pod this deployment runs/monitors
    template:
        metadata:
            labels:
                component: server
        spec:
            containers:
                - name: server
                  image: redridinghood/docker-complex-fib-server
                  ports:
                    - containerPort: 5000
                  env:
                    - name: REDIS_HOST
                      value: redis-cluster-ip-service
                    - name: REDIS_PORT
                      value: '6379'
                    - name: PGUSER
                      value: postgres
                    - name: PGHOST
                      value: postgres-cluster-ip-service
                    - name: PGPORT
                      value: '5432'
                    - name: PGDATABASE
                      value: postgres
                    - name: PGPASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: pgpassword
                          key: POSTGRES_PASSWORD